apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocdtest
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: https://github.com/IsaSubhi/argocd_test.git
    targetRevision: HEAD
    path: argocdtest
  destination:
    server: https://kubernetes.default.svc
    namespace: myappargocd-ns
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true