apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: isasubhi/my-nginx-container:1.2
        ports:
        - containerPort: 80